packages:
  - software 
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.46.0
  "@platforma-sdk/ui-vue": ^1.46.1
  "@platforma-sdk/workflow-tengo": ^5.6.4
  "@platforma-sdk/block-tools": ^2.6.25
  "@platforma-sdk/test": ^1.46.3
  "@platforma-sdk/tengo-builder": ^2.3.14
  "@platforma-sdk/package-builder": ^3.10.7
  "@platforma-sdk/eslint-config": ^1.1.0
  '@milaboratories/multi-sequence-alignment': ^1.45.5
  "@platforma-sdk/blocks-deps-updater": ^2.0.0


  "@milaboratories/graph-maker": ^1.1.191
  "@platforma-open/milaboratories.runenv-python-3": ^1.4.9
  "@platforma-open/milaboratories.software-small-binaries": ^1.15.23
  '@platforma-open/milaboratories.runenv-r-differential-expression': ^1.0.7
  "@platforma-open/milaboratories.runenv-r": ^1.2.18
  "@milaboratories/software-pframes-conv": ^2.2.9
  
  "vue": ^3.5.24
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.4.0
  "turbo": ^2.4.4

  "vite": ^6.2.2
  "vitest": ^3.0.9
  "@vitejs/plugin-vue": ^5.2.3


  "@changesets/cli": ^2.28.1
